import { jsPDF } from 'jspdf';
import type { DonationItem } from '../types/index.ts';

const GREEN = [16, 185, 129] as const; // emerald-500
const DARK = [17, 24, 39] as const;    // gray-900
const GRAY = [75, 85, 99] as const;    // gray-600
const LIGHT_BG = [236, 253, 245] as const; // emerald-50

function formatValue(item: DonationItem): string {
  if (!item.impact.estimatedValue) return 'N/A';
  const currency = item.impact.currency ?? 'PHP';
  return `${currency} ${item.impact.estimatedValue.toLocaleString()}`;
}

export function downloadImpactReport(item: DonationItem, seekerOrg: string) {
  const doc = new jsPDF({ unit: 'mm', format: 'a4' });
  const pageW = doc.internal.pageSize.getWidth();
  const margin = 20;
  const contentW = pageW - margin * 2;
  let y = 20;

  // ── Header bar ──
  doc.setFillColor(...GREEN);
  doc.rect(0, 0, pageW, 38, 'F');
  doc.setTextColor(255, 255, 255);
  doc.setFontSize(22);
  doc.setFont('helvetica', 'bold');
  doc.text('RESOURCECYCLE', margin, 16);
  doc.setFontSize(11);
  doc.setFont('helvetica', 'normal');
  doc.text('Impact Report', margin, 24);
  doc.setFontSize(9);
  doc.text(new Date().toLocaleDateString('en-PH', { year: 'numeric', month: 'long', day: 'numeric' }), margin, 32);
  y = 48;

  // ── Section helper ──
  function sectionTitle(title: string) {
    doc.setFillColor(...GREEN);
    doc.rect(margin, y, contentW, 8, 'F');
    doc.setTextColor(255, 255, 255);
    doc.setFontSize(11);
    doc.setFont('helvetica', 'bold');
    doc.text(title, margin + 3, y + 5.5);
    y += 12;
  }

  function bodyText(text: string) {
    doc.setTextColor(...GRAY);
    doc.setFontSize(10);
    doc.setFont('helvetica', 'normal');
    const lines = doc.splitTextToSize(text, contentW);
    doc.text(lines, margin, y);
    y += lines.length * 5 + 4;
  }

  function metricRow(label: string, value: string) {
    doc.setTextColor(...DARK);
    doc.setFontSize(10);
    doc.setFont('helvetica', 'bold');
    doc.text(label, margin + 2, y);
    doc.setFont('helvetica', 'normal');
    doc.text(value, margin + 48, y);
    y += 6;
  }

  // ── 1. Executive Summary ──
  sectionTitle('1. EXECUTIVE SUMMARY');
  bodyText(
    `${seekerOrg} has claimed "${item.name}" (x${item.quantity}) donated by ${item.donorName}. ` +
    'This donation has been matched through ResourceCycle, turning surplus resources into measurable social impact.',
  );

  // ── 2. High-Level Metrics ──
  sectionTitle('2. HIGH-LEVEL METRICS');
  doc.setFillColor(...LIGHT_BG);
  doc.rect(margin, y - 2, contentW, 52, 'F');
  metricRow('Item:', item.name);
  metricRow('Quantity:', String(item.quantity));
  metricRow('Category:', item.category);
  metricRow('Donor:', item.donorName);
  metricRow('Claiming Org:', seekerOrg);
  metricRow('People Helped:', String(item.impact.peopleHelped ?? 'N/A'));
  metricRow('Estimated Value:', formatValue(item));
  metricRow('SDGs Addressed:', item.impact.sdgs.map((s) => `SDG ${s.number}: ${s.name}`).join(', '));
  y += 4;

  // ── 3. Human Story ──
  sectionTitle('3. HUMAN STORY');
  bodyText(item.impact.text);
  const narrative = item.category === 'Tech Equipment'
    ? 'Technology donations bridge the digital divide — giving students and communities access to tools that unlock education, employment, and innovation opportunities they would otherwise never have.'
    : 'Furniture donations create dignified learning and working spaces — when children have proper desks and chairs, attendance rises, focus improves, and communities build the foundations for lasting growth.';
  bodyText(narrative);

  // ── 4. Financial Transparency ──
  sectionTitle('4. FINANCIAL TRANSPARENCY');
  bodyText('ResourceCycle Allocation Model:');
  const allocations = [
    ['85%', 'Direct program delivery'],
    ['10%', 'Logistics & matching'],
    ['5%', 'Platform administration'],
  ];
  for (const [pct, desc] of allocations) {
    doc.setTextColor(...DARK);
    doc.setFontSize(10);
    doc.setFont('helvetica', 'bold');
    doc.text(`${pct}`, margin + 6, y);
    doc.setFont('helvetica', 'normal');
    doc.setTextColor(...GRAY);
    doc.text(`— ${desc}`, margin + 18, y);
    y += 6;
  }
  y += 4;

  // ── 5. Future Goals ──
  sectionTitle('5. FUTURE GOALS');
  bodyText(
    'ResourceCycle aims to expand across the Philippines, connecting more donors with schools, orphanages, and community organizations. ' +
    'Every item diverted from waste becomes a building block for education and opportunity.',
  );

  // ── Footer ──
  doc.setDrawColor(...GREEN);
  doc.setLineWidth(0.5);
  doc.line(margin, y + 2, pageW - margin, y + 2);
  y += 8;
  doc.setTextColor(...GREEN);
  doc.setFontSize(9);
  doc.setFont('helvetica', 'italic');
  doc.text('Generated by ResourceCycle — Turning Surplus Into Impact', margin, y);

  // ── Download ──
  const filename = `ResourceCycle_Impact_${item.name.replace(/\s+/g, '_')}_${seekerOrg.replace(/\s+/g, '_')}.pdf`;
  doc.save(filename);
}
